"""Initial migration

Revision ID: 2214aa197af9
Revises: 
Create Date: 2024-05-18 11:12:24.780856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2214aa197af9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_id'), 'workflow', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_name'), 'workflow', ['name'], unique=False)
    op.create_table('node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('start', 'message', 'condition', 'end', name='nodetype'), nullable=True),
    sa.Column('status', sa.Enum('pending', 'sent', 'opened', name='nodestatus'), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_id'), 'node', ['id'], unique=False)
    op.create_table('edge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_node_id', sa.Integer(), nullable=True),
    sa.Column('end_node_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['end_node_id'], ['node.id'], ),
    sa.ForeignKeyConstraint(['start_node_id'], ['node.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edge_id'), 'edge', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_edge_id'), table_name='edge')
    op.drop_table('edge')
    op.drop_index(op.f('ix_node_id'), table_name='node')
    op.drop_table('node')
    op.drop_index(op.f('ix_workflow_name'), table_name='workflow')
    op.drop_index(op.f('ix_workflow_id'), table_name='workflow')
    op.drop_table('workflow')
    # ### end Alembic commands ###
