"""Updated Workflow, Node, and Edge models

Revision ID: 51714b974b7e
Revises: 2214aa197af9
Create Date: 2024-05-18 14:11:22.090315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51714b974b7e'
down_revision: Union[str, None] = '2214aa197af9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
